version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.452.2-lts
    container_name: jenkins-lts
    ports:
      - '8080:8080'
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_data:
