export enum Configuration {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  NODE_NAME = 'NODE_NAME',
  // MySQL configuration
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
  // RabbitMQ configuration
  RABBITMQ_URL = 'RABBITMQ_URL',
  RABBITMQ_QUEUE = 'RABBITMQ_QUEUE',
}
